version: '3'
services:
  api:
    image: fortune-api
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
    networks:
      - fortune-api

  mongo:
    image: mongo:5
    # environment:
    #   - MONGO_INITDB_DATABASE=test
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - fortune-api

networks:
  fortune-api:
